#ifndef __ORIONSOCKET_ERR_
#define __ORIONSOCKET_ERR_

#define ORIONSOCKET_ERR_UNKNOWN         0x01
#define ORIONSOCKET_ERR_ALLOC           0x02
#define ORIONSOCKET_ERR_HTTPREQUEST     0X03
#define ORIONSOCKET_INVALIDHOST         0x04
#define ORIONSOCKET_INVALIDHTTPREQUEST  0x05

#endif // __ORIONSOCKET_ERR_
